---
title: "styling code properly"
author: "Gregory Park"
date: "2026-03-01"
output: github_document
---
command + shift + p is a useful shortcut
```{r, message=FALSE}
library(styler); library(tidyverse); library(nycflights13)
```
variable names: lowercase, underscores, descriptive > short

make operations well spaced out
```{r}
# Strive for
z <- (1 + 2)^2 / 4

# Avoid
z<-( 1 + 2 ) ^ 2/4
```

new arguments on new lines
```{r, results='hide'}
# Strive for
flights |>  
  group_by(tailnum) |> 
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )

# Avoid
flights |>
  group_by(
    tailnum
  ) |> 
  summarize(delay = mean(arr_delay, na.rm = TRUE), n = n())

# Strive for 
flights |>  
  group_by(tailnum) |> 
  summarize(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )

# Avoid
flights|>
  group_by(tailnum) |> 
  summarize(
             delay = mean(arr_delay, na.rm = TRUE), 
             n = n()
           )

# Avoid
flights|>
  group_by(tailnum) |> 
  summarize(
  delay = mean(arr_delay, na.rm = TRUE), 
  n = n()
  )
```
Break long pipes into smaller named subgroups

When using ggplot, follow similar conventions
```{r, warning=FALSE}
flights |> 
  group_by(dest) |> 
  summarize(
    distance = mean(distance),
    speed = mean(distance / air_time, na.rm = TRUE)
  ) |> 
  ggplot(aes(x = distance, y = speed)) +
  geom_smooth(
    method = "loess",
    span = 0.5,
    se = FALSE, 
    color = "red", 
    linewidth = 4
  ) +
  geom_point()
```

formatting exercise:
```{r}
flights |> 
  filter(dest == "IAH") |> 
  group_by(year, month, day) |> 
  summarise(
    n = n(),
    delay = mean(arr_delay, na.rm = TRUE)
  ) |> 
  filter(n > 10)

flights |> 
  filter(
    carrier == "UA",
    dest %in% c("IAH", "HOU"),
    sched_dep_time > 0900,
    sched_arr_time < 2000
  ) |> 
  group_by(flight) |> 
  summarise(
    delay = mean(arr_delay, na.rm = TRUE),
    cancelled = sum(is.na(arr_delay)),
    n = n()
  ) |> 
  filter(n > 10)
```

